check for git checkout failure

diff --git a/bin/bbbike-merge b/bin/bbbike-merge
--- a/bin/bbbike-merge
+++ b/bin/bbbike-merge
@@ -7,7 +7,12 @@ cd $dir
 
 exec 2> log.bbbike
 
-bbbike-checkout
+if ! bbbike-checkout; then
+    echo "checkout failed: $dir"
+    cat log.bbbike
+    exit 2
+fi
+
 cd bbbike
 
 git merge eserte/master
