remove tailing spaces

diff --git a/bin/bbbike-build-runtime b/bin/bbbike-build-runtime
--- a/bin/bbbike-build-runtime
+++ b/bin/bbbike-build-runtime
@@ -49,7 +49,7 @@ do
     if which $c >/dev/null; then
         :
     else
-        echo "missing command $c" >&2 
+        echo "missing command $c" >&2
         error=1
     fi
 done
@@ -76,3 +76,5 @@ else
 fi
 
 exit $error
+
+#EOF
diff --git a/bin/check-data-osm b/bin/check-data-osm
--- a/bin/check-data-osm
+++ b/bin/check-data-osm
@@ -10,10 +10,12 @@
 set -e
 
 city=$1
-if ! find $DATA_OSM_DIR/$city -type f -print | egrep -v '\.(gz|bak|dd|yml|pl|data)$$' | 
-	 egrep -v 'opensearch\.' | sort -r | xargs -n1 -P$MAX_CPU  ./miscsrc/grepstrassen -name Kreuzbergstr. >/dev/null; 
-then 
-     echo "Failed city: $city"
-     exit 1
+if ! find $DATA_OSM_DIR/$city -type f -print | egrep -v '\.(gz|bak|dd|yml|pl|data)$$' |
+  egrep -v 'opensearch\.' | sort -r | xargs -n1 -P$MAX_CPU  ./miscsrc/grepstrassen -name Kreuzbergstr. >/dev/null
+then
+  echo "Failed city: $city"
+  exit 1
 fi
+
+#EOF
 
