in case of an error display log message

diff --git a/bin/osm2bbbike b/bin/osm2bbbike
--- a/bin/osm2bbbike
+++ b/bin/osm2bbbike
@@ -99,10 +99,15 @@ $text2html < README.txt > README.html
 
 OSM2BBD_OPT="--ignore-unhandled --ignore-underline-noname --granularity=100"
 OSM2BBD_MAPTYPE="-map bbbike"
-$dirname/../../miscsrc/osm2bbd ${OSM2BBD_OPT} --nodate --no-create --git-id="${GIT_ID}" \
+
+if $dirname/../../miscsrc/osm2bbd ${OSM2BBD_OPT} --nodate --no-create --git-id="${GIT_ID}" \
     -f --debug=0 ${OSM2BBD_MAPTYPE} \
     -experiment add_postal_code -experiment handle_relations \
-    -lang $BBBIKE_EXTRACT_LANG -o bbbike-data $file >> $logfile 2>&1
+    -lang $BBBIKE_EXTRACT_LANG -o bbbike-data $file >> $logfile 2>&1; then
+    :
+else
+    error "osm2bbd failed with exit status: $?"
+fi
 
 case $BBBIKE_EXTRACT_LANG in
   en ) ext2=$ext ;;
