cleanup /tmp directory after signal, but show errors first

diff --git a/bin/osm2garmin b/bin/osm2garmin
--- a/bin/osm2garmin
+++ b/bin/osm2garmin
@@ -122,6 +122,10 @@ if [ -n "$mkgmap_map_type" ]; then
 fi
 
 tmpdir=`mktemp -d ${TMPDIR-"/tmpfs"}/garmin.$(basename $ext .zip).XXXXXXXXXXX`
+
+# cleanup after signal, but show errors first
+trap '( sleep 1; rm -rf $tmpdir ) &' 1 2 15
+
 split_dir=$tmpdir/split
 mkdir -p $split_dir
 
diff --git a/bin/osm2navit b/bin/osm2navit
--- a/bin/osm2navit
+++ b/bin/osm2navit
@@ -50,7 +50,12 @@ if [ -e /tmpfs ]; then
 else
     _tmp=/bbbike/tmp
 fi
+
 tmpdir=`mktemp -d ${TMPDIR-"$_tmp"}/osm2navit.XXXXXXXXXXX`
+
+# cleanup after signal, but show errors first
+trap '( sleep 1; rm -rf $tmpdir ) &' 1 2 15
+
 navit=`basename $file | perl -npe 's/\.osm(\.pbf|\.gz|\.bz2)?$//'`
 navit_dir=$tmpdir/${navit}-navit
 mkdir -p $navit_dir
diff --git a/bin/osm2osmand b/bin/osm2osmand
--- a/bin/osm2osmand
+++ b/bin/osm2osmand
@@ -57,7 +57,12 @@ if [ -e /tmpfs ]; then
 else
     _tmp=/bbbike/tmp
 fi
+
 tmpdir=`mktemp -d ${TMPDIR-"$_tmp"}/osm2obf.XXXXXXXXXXX`
+
+# cleanup after signal, but show errors first
+trap '( sleep 1; rm -rf $tmpdir ) &' 1 2 15
+
 obf=`basename $file | perl -npe 's/\.osm(\.pbf|\.gz|\.bz2)?$//'`
 obf_dir=$tmpdir/${obf}-obf
 mkdir -p $obf_dir
