first version

diff --git a/bin/osm2obf b/bin/osm2obf
--- a/bin/osm2obf
+++ b/bin/osm2obf
@@ -25,25 +25,30 @@ pwd=$(pwd)
 
 test -z "$file" && usage
 
-tmpdir=`mktemp -d ${TMPDIR-"/bbbike/tmp"}/osmium2shape.XXXXXXXXXXX`
-garmin=`basename $file | perl -npe 's/\.osm(\.pbf|\.gz|\.bz2)?$//'`
-garmin_dir=$tmpdir/$garmin
-mkdir -p $garmin_dir
+tmpdir=`mktemp -d ${TMPDIR-"/bbbike/tmp"}/osm2obp.XXXXXXXXXXX`
+obf=`basename $file | perl -npe 's/\.osm(\.pbf|\.gz|\.bz2)?$//'`
+obf_dir=$tmpdir/$obf
+mkdir -p $obf_dir
 
-logfile=$garmin_dir/logfile.txt 
+etc_dir=`dirname $0`/../etc/OsmAndMapCreator
+logfile=$obf_dir/logfile.txt 
 
 file_basename=`basename $file`
-file_fixme=$garmin_dir/$file_basename
-if osmosis --read-pbf $file --bb left=-180 right=180 top=90 bottom=-90 clipIncompleteEntities=true --write-pbf omitmetadata=true $file_fixme > $logfile 2>&1; then
-   :
-else
-   exit=$?
-   echo "Failed to fix $file"
-   cat $logfile
-   exit $exit
-fi
+#file_fixme=$obf_dir/$file_basename
+#if osmosis --read-pbf $file --bb left=-180 right=180 top=90 bottom=-90 clipIncompleteEntities=true --write-pbf omitmetadata=true $file_fixme > $logfile 2>&1; then
+#   :
+#else
+#   exit=$?
+#   echo "Failed to fix $file"
+#   cat $logfile
+#   exit $exit
+#fi
 
-if osmium2shape -d $garmin_dir $file_fixme > $logfile 2>&1; then
+cd $obf_dir
+mkdir data data/osm data/out data/indexes
+( cd data/osm; ln -s $file . )
+
+if java -Xmx2048M -Xmn256M -Djava.util.logging.config.file=$etc_dir/osm2obf-logging.properties -cp $HOME/opt/OsmAndMapCreator-0.6.8.2-beta/OsmAndMapCreator.jar:$HOME/opt/OsmAndMapCreator-0.6.8.2-beta/lib/*.jar net.osmand.data.index.IndexBatchCreator $etc_dir/osm2obf.xml > $logfile 2>&1; then
    :
 else
    exit=$?
@@ -51,19 +56,18 @@ else
    cat $logfile
    exit $exit
 fi
-rm -f $file_fixme
 
-cd $garmin_dir
+#rm -f $file_fixme
+
 
 cat << EOF > README.txt
 Map data (c) OpenStreetMap contributors, http://www.openstreetmap.org
 Extracts created by BBBike.org
-osmium2shape by Geofabrik, http://geofabrik.de
+OsmAnd by osmand.net, http://code.google.com/p/osmand
 
-Please read the OSM wiki how to use shape files.
+Please read the OsmAnd homepage how to use obf files:
 
-  http://wiki.openstreetmap.org/wiki/Shapefiles
-
+  http://osmand.net
 
 thanks, Wolfram Schneider
 
@@ -73,13 +77,13 @@ We appreciate any feedback, suggestions and a donation!
 EOF
 
 cd ..
-garmin_zip=`dirname $file`/$garmin.osm.shp.zip
-zip -q -r - -- $garmin | \
+zip_file=`dirname $file`/$obf.osm.obf.zip
+zip -q -r - -- $obf | \
   ( cd $pwd;
-    cat > $garmin_zip.tmp && mv $garmin_zip.tmp $garmin_zip 
-    $md5sum $garmin_zip > $garmin_zip.md5
-    $SHA $garmin_zip > $garmin_zip.sha256
+    cat > $zip_file.tmp && mv $zip_file.tmp $zip_file 
+    $md5sum $zip_file > $zip_file.md5
+    $SHA $zip_file > $zip_file.sha256
   )
 
-$debug || rm -rf $tmpdir
+#$debug || rm -rf $tmpdir
 
