correct pdf files

diff --git a/bin/osm2obf b/bin/osm2obf
--- a/bin/osm2obf
+++ b/bin/osm2obf
@@ -37,22 +37,22 @@ case $etc_dir in /* ) ;; *) etc_dir=$pwd/$etc_dir ;; esac
 
 logfile=$obf_dir/logfile.txt 
 
+mkdir $obf_dir/data $obf_dir/data/osm $obf_dir/data/indexes
 file_basename=`basename $file`
-#file_fixme=$obf_dir/$file_basename
-#if osmosis --read-pbf $file --bb left=-180 right=180 top=90 bottom=-90 clipIncompleteEntities=true --write-pbf omitmetadata=true $file_fixme > $logfile 2>&1; then
-#   :
-#else
-#   exit=$?
-#   echo "Failed to fix $file"
-#   cat $logfile
-#   exit $exit
-#fi
+file_fixme=$obf_dir/data/osm/$file_basename
+if osmosis --read-pbf $file --bb left=-180 right=180 top=90 bottom=-90 clipIncompleteEntities=true --write-pbf omitmetadata=true $file_fixme > $logfile 2>&1; then
+   :
+else
+   exit=$?
+   echo "Failed to fix $file"
+   cat $logfile
+   exit $exit
+fi
 
 cd $obf_dir
-mkdir data data/osm data/out data/indexes
-( cd data/osm; ln -s $file . )
+#( cd data/osm; ln -s $file . )
 
-if java -Xmx2048M -Xmn256M -Djava.util.logging.config.file=$etc_dir/osm2obf-logging.properties -cp $HOME/opt/OsmAndMapCreator-0.6.8.2-beta/OsmAndMapCreator.jar:$HOME/opt/OsmAndMapCreator-0.6.8.2-beta/lib/*.jar net.osmand.data.index.IndexBatchCreator $etc_dir/osm2obf.xml > $logfile 2>&1; then
+if time java -Xmx2048M -Xmn256M -Djava.util.logging.config.file=$etc_dir/osm2obf-logging.properties -cp $HOME/opt/OsmAndMapCreator-0.6.8.2-beta/OsmAndMapCreator.jar:$HOME/opt/OsmAndMapCreator-0.6.8.2-beta/lib/*.jar net.osmand.data.index.IndexBatchCreator $etc_dir/osm2obf.xml > $logfile 2>&1; then
    :
 else
    exit=$?
@@ -91,5 +91,5 @@ zip -q -r - -- $obf | \
     $SHA $zip_file > $zip_file.sha256
   )
 
-#$debug || rm -rf $tmpdir
+$debug || rm -rf $tmpdir
 
