default local languge is "de"

diff --git a/bin/osm2bbd-workarounds b/bin/osm2bbd-workarounds
--- a/bin/osm2bbd-workarounds
+++ b/bin/osm2bbd-workarounds
@@ -17,7 +17,12 @@ p=`pwd`/world/bin
 perl ./miscsrc/osm2bbd-postprocess --debug=0 \
 	-only-largest-city-is-center \
 	-skip-inaccessible-streets \
-	--local-lang="`world/bin/bbbike-db --local-lang $city`" $prefix/$city
+	--local-lang=`world/bin/bbbike-db --local-lang $city` $prefix/$city
+
+if [ $? != 0 ]; then
+	echo "failed $city"
+	exit $?
+fi
 
 cd $prefix/$city || exit 2
 
