support to convert more pbf files at once

diff --git a/bin/pbf2osm b/bin/pbf2osm
--- a/bin/pbf2osm
+++ b/bin/pbf2osm
@@ -41,18 +41,47 @@ fi
 # run in quiet mode
 global_opt=-q
 
+osm2osm () {
+compressionMethod=$1
+shift
+case $compressionMethod in
+  gzip ) ext=.gz ;;
+  bzip2 ) ext=.bz2 ;;
+  * ) echo "unknown compress $compressionMethod"; exit 2;;
+esac
+
+args=""
+for f 
+do
+   ff=`echo $f | sed "s/\.pbf$/$ext.tmp/"`
+   args="$args --read-pbf $f --write-xml $ff compressionMethod=$compressionMethod"
+done
+
+
+if osmosis $global_opt $args 
+then
+    for f 
+    do
+        ff=`echo $f | sed "s/\.pbf$/$ext/"`
+        mv -f $ff.tmp $ff
+        chmod 664 $ff
+    done
+else
+    echo "File $@ failed"
+    exit 2
+fi 
+}
+
+
+
 if [ "$compress" = "" ]; then
     osmosis $global_opt --read-pbf "$file" --write-xml /dev/stdout 
 else
     f=`basename $file .pbf`
     dir=`dirname $file`
     case $compress in
-	gzip ) osmosis $global_opt --read-pbf "$file" --write-xml /dev/stdout | $gzip > $dir/$f.tmp 
-		mv -f $dir/$f.tmp $dir/$f.gz		
-		;;
-	bzip2 ) osmosis $global_opt --read-pbf "$file" --write-xml /dev/stdout | $bzip2 > $dir/$f.tmp 
-		mv -f $dir/$f.tmp $dir/$f.bz2		
-		;;
+	gzip )  osm2osm $compress "$@";;
+	bzip2 ) osm2osm $compress "$@";;
 	xz ) osmosis $global_opt --read-pbf "$file" --write-xml /dev/stdout | $xz $xz_opt > $dir/$f.tmp 
 		mv -f $dir/$f.tmp $dir/$f.xz		
 		;;
