rewritten to work even if we do not keep the original planet.osm file

diff --git a/bin/planet-download-alert b/bin/planet-download-alert
--- a/bin/planet-download-alert
+++ b/bin/planet-download-alert
@@ -10,10 +10,10 @@ set -o pipefail
 
 PATH=/usr/local/bin:/bin:/usr/bin; export PATH 
 
-
 file=planet-latest.osm.pbf
-automatic_update="yes"
 planet_osm_server=https://planet.openstreetmap.org/planet
+
+automatic_update="yes"
 bbbikerc=$HOME/.bbbikerc
 planet_osm_min_size=33000600300
 
@@ -21,14 +21,14 @@ if [ -e "$bbbikerc" ]; then
     . "$bbbikerc"
 fi
 
-old="0"
-new="1"
 dir=../osm/download
+
 update=$dir/.update
 update_new=$dir/.update.new
+update_lock=$dir/.update.lock
 
 #
-# don't run again if already run in the last 48 hours
+# don't run again if there was a run in the last 48 hours
 # This should avoid DoS and too many updates
 #
 if [ -e $update ]; then
@@ -37,25 +37,43 @@ if [ -e $update ]; then
    fi
 fi
 
+if [ -e $update_lock ]; then
+  # still running
+  exit 0
+fi
+
 curl -L -sSf -v $planet_osm_server/$file.md5 > $update_new 2> $update_new.head
 
+# we compare the MD5 checksum of the original planet.osm file
 if test -e $update && cmp $update $update_new 2>/dev/null ; then
    # no updates....
    exit 0
+
 else
    new=$(curl -L -sSf --head --location $planet_osm_server/$file | perl -ne 'print "$1\n" if /^Content-Length:\s+(\d+)/i')
    echo "please update me: $planet_osm_server/$file"
    echo ""
    curl -L -sSf --head --location $planet_osm_server/$file | egrep -i "^(Content-Length:|Last-|Location:)"
-   cp -f $update_new $update
 
    if [ -n "$automatic_update" ]; then
      if [ $new -gt $planet_osm_min_size ]; then
+       touch $update_lock
        echo "start updated: $(date), may run 8-21 hours"
-       logfile=tmp/log.update-database
-       make -s update-database > $logfile 2>&1 || tail -n 200 $logfile 
-       echo "done updated: $(date)"
        echo "hostname: $(hostname), IP: $(egrep $(hostname) /etc/hosts)"
+       logfile=tmp/log.update-database
+
+       if make -s update-database > $logfile 2>&1; then
+         echo "done updated: $(date)"
+         cp -f $update_new $update
+
+	 # cleanup lock file on success
+	 rm -f $update_lock
+       else 
+	 tail -n 200 $logfile 
+         echo "failed: $(date)"
+         exit 1
+       fi
+
      else
        echo "planet.osm size to small: $new < $planet_osm_min_size"
        exit 1
